backend:
  name: git-gateway
  branch: develop

media_folder: "media"
publish_mode: editorial_workflow

collections:
  - name: "doc"
    label: "Documents"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "string"}
